### PR TITLE
Send sphinx.conf as plaintext

### PR DESCRIPTION
**Pull request by ghost**
The sphinx.conf is just plaintext so sending it as text/plain. This also allows to directly view the file from e.g. Firefox within the download dialog.

I have also removed the Accept-Range: bytes as there is no need for byte-range requests here.

### CODE REVIEW

**Comment by ghost** [comment]
Its also the question if other sent headers could be stripped away. Any opinion about this?

**Comment by jdarwood007** [comment]
Most of those headers are derived from our Display.php download function which handles downloading attachments.
I sent it as octetstream as it forces the browser to imitate a download.  This is common practice to do in web development if you want to start a download.

I'm unsure on this.  On one hand, it makes it easy as you can just upload the sphinx.conf, on the other viewing it makes it easier to copy and paste into a terminal shell window that has nano or vi with the file open.

**Comment by ghost** [comment]
The download within the browser is still happening here like before. You're just able to have an additional "Open with" field within your browser like http://weblog.west-wind.com/images/2013Windows-Live-Writer/Downloading-a-File-with-a-Save-As-Di.NET_735/SaveAsDialog_thumb_1.png

**Comment by jdarwood007** [comment]
I committed a change which allows both options.  More novice users may have issues with having to tell the browser to specifically download a file.

**Comment by ghost** [comment]
Also fine with that, providing both ways is even better :+1: 

Only the $txt['sphinx_view_config'] seems to be missing in the language-file?

**Comment by jdarwood007** [comment]
My bad, it didn't sync from my test site.

**Pull request closed without merging**
